Merge Sort Implementation for Computer Vision Bootcamp
UWARG/autonomy-bootcamp pull request #10
Opened 2018-01-17 15:53 UTC by vsivan97

2018-01-17 21:20 UTC, benjaminwinger requested changes
Looks good in general, though you need to add the module to the list of modules in the root CMakeLists.txt file. Currently your code isn't actually being compiled and your test isn't being run.

2018-01-18 12:45 UTC, vsivan97 commented
Hi, I made the changes requested. For the linker issue with the template function, I modified the functions themselves for simplicity's sake.

2018-01-19 01:05 UTC, benjaminwinger commented on modules/sort/test/test.cpp
> +    BOOST_TEST(example[i] == soln[i]);
The BOOST_TEST macro was actually added in 1.59, however the build server is using 1.58 (I'm in the process of updating it).
Noting that we are planning on using features introduced in boost 1.62, this isn't exactly an issue, so this is fine, but that's why the build server is reporting a failure.

2018-01-19 01:08 UTC, benjaminwinger commented
I've added you to Asana, so you can now take a look at the tasks that need to be done. You should probably start with a task marked beginner, as those require less familiarity with the existing code. If you want any suggestions as to what to choose, feel free to contact me on slack. You also should probably let me know before you start working on something just because some of the tasks are a little out of date.

2018-01-19 01:08 UTC, closed without merging