mafatakd bootcamp
UWARG/autonomy-bootcamp pull request #6
Opened 2017-06-09 15:31 UTC by mafatakd

Murtaza's bootcamp for the UWARG computer vision team.

2017-06-10 00:14 UTC, benjaminwinger requested changes
There are a couple necessary changes that I've outlined, but it looks good in general.

2017-06-10 00:14 UTC, benjaminwinger commented on modules/mergesort/include/merge_sort.h
> + // @brief uses mergesort to sort the vector that is inputted
Doxygen requires that you use doc-style comments, either `/** */` such as in the file header or `///` if you want to use c++ style comments. If you don't it won't use the comment in the generated documentation.

2017-06-12 14:14 UTC, mafatakd commented on modules/mergesort/src/merge_sort.cpp
> +// int main(){
Alright, thanks I'll make all the necessary changes.

2017-06-12 22:27 UTC, benjaminwinger approved these changes
Looks good. Merging this and will send you an invitation to Asana (the task management system we use)

2017-06-12 22:27 UTC, benjaminwinger commented on modules/mergesort/include/merge_sort.h
> + *  inthis software is licensed under a modified version of the BSD 3 clause license
Didn't see this before. Just a typo, and given this is the bootcamp you can ignore this now.

2017-06-12 22:28 UTC, merged