WARG Onboarding Submission - Jomills Jose Anand
UWARG/autonomy-bootcamp pull request #85
Opened 2022-05-13 19:45 UTC by jomillsjoseanand

Built a classification model using TensorFlow to classify the CIFAR-10 dataset. Generated a plot to check for loss and accuracy as the model trained and achieved an overall accuracy of 78.21%.

This is my onboarding submission for the WARG Computer Vision Team. Check it out and let me know in case there's anything I can change or do better. Thanks! 

![image](https://user-images.githubusercontent.com/44730936/168378538-80c5ab9e-7367-4649-804d-84dae4114704.png)

![plot](https://user-images.githubusercontent.com/44730936/168378566-0393e030-34cf-42ba-a8c5-d8bea773eb7f.png)

2022-05-17 23:43 UTC, rayjinghaolei requested changes

2022-05-17 23:43 UTC, rayjinghaolei commented on main.py
> +def create_model(xTrain, yTest):
just a small thing here, you can only pass in the required shape for xTrain and yTest instead of passing all of them

2022-05-17 23:43 UTC, rayjinghaolei commented on main.py
> +def create_model(xTrain, yTest):
other wise all good here, good job, this is beautiful code

2022-05-18 01:02 UTC, jomillsjoseanand commented
I have updated the function to only accept the shapes of xTrain and yTest as arguments. Kindly check it out and provide me any further feedback. Thanks!

2022-05-18 01:07 UTC, rayjinghaolei commented
Good job, welcome to the team, First CV meeting is May 26th @7pm see you there

2022-05-18 01:07 UTC, closed without merging